apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: workshop-cluster
  region: us-east-2
  version: "1.33" # Specify the EKS version

managedNodeGroups:
  - name: system-managed-ng
    instanceType: t2.micro
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]
    labels:
      role: worker
    privateNetworking: true

addonsConfig:
  autoApplyPodIdentityAssociations: true
# bear in mind that if either pod identity or IRSA configuration is explicitly set in the config file,
# or if the addon does not support pod identities,
# addonsConfig.autoApplyPodIdentityAssociations won't have any effect.
addons:
- name: vpc-cni
- name: coredns
- name: kube-proxy
- name: eks-pod-identity-agent
