apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-app
  labels:
    app: workshop-app
spec:
  replicas: 2 # Run two instances for availability
  selector:
    matchLabels:
      app: workshop-app
  template:
    metadata:
      labels:
        app: workshop-app
    spec:
      containers:
        - name: workshop-app
          # IMPORTANT: This is a placeholder. Our pipeline will replace it.
          image: "IMAGE_PLACEHOLDER"
          ports:
            - containerPort: 8080
          # --- Security Context ---
          # This enforces security best practices at the container level.
          securityContext:
            # Prevents the container from gaining more privileges than its parent process.
            allowPrivilegeEscalation: false
            # Runs the container with a read-only root filesystem.
            readOnlyRootFilesystem: true
            # Specifies the user and group IDs to run as, matching our Dockerfile.
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            # Drops all Linux capabilities and only adds back what's necessary (none in this case).
            capabilities:
              drop:
                - "ALL"
      # Location for temporary files, as the root filesystem is read-only.
      volumes:
        - name: tmp
          emptyDir: {}
