apiVersion: v1
kind: Service
metadata:
  name: workshop-app-service
spec:
  selector:
    app: workshop-app
  # This type creates an external AWS Load Balancer
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # The port the load balancer listens on
      targetPort: 8080 # The port the container listens on
