apiVersion: v1
kind: Service
metadata:
  name: workshop-app-service
spec:
  # This type creates an external AWS Load Balancer
  type: LoadBalancer
  selector:
    app: workshop-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
