apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  # Add a finalizer so that you can delete the app and all its resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # This points to the repository you are in right now!
    repoURL: "https://github.com/powoftech/eks-istio-workshop.git" # <-- IMPORTANT: Change this!
    targetRevision: HEAD
    path: config/apps # Tells ArgoCD to look for app manifests in the 'apps' directory
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
