apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  # Add a finalizer so that ArgoCD deletes the apps it manages before deleting itself
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/powoftech/eks-istio-workshop.git"
    targetRevision: HEAD
    path: config/apps # This app will manage other apps defined in the 'apps' directory
  destination:
    server: "https://kubernetes.default.svc" # This means the local cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
