baseURL = 'https://example.org/'
theme = 'hugo-theme-relearn'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en-us'
    languageName = 'English'
    title = 'Container Registry Security with Vulnerability Scanning and Policy Enforcement'
    weight = 1

  [languages.vi]
    languageCode = 'vi-vn'
    languageName = 'Tiếng Việt'
    title = 'Bảo mật Container Registry với Quét lỗ hổng và Thực thi chính sách'
    weight = 2

[params]
  disableLandingPageButton = true
  hideAuthorDate = true
  showVisitedLinks = true
  themeVariant = "learn"

[menu]
  [[menu.shortcuts]]
    pre = '<i class="fa-brands fa-square-facebook"></i> '
    name = 'AWS Study Group'
    url = 'https://www.facebook.com/groups/660548818043427'
    weight = 1

